# Step 1.1

In [132]:
# Используйте print() чтобы распечатать получившийся pd.Series.

import pandas as pd

lst = list('zyxwvutsr')
ser = pd.Series(lst)
ser

0    z
1    y
2    x
3    w
4    v
5    u
6    t
7    s
8    r
dtype: object

In [133]:
# На основе листа lst и массива arr сформируйте словарь и cоздайте pandas.Series из получившегося словаря.

import numpy as np
import pandas as pd

lst = list('abced')
arr = np.arange(5)
pd.Series(arr, index=lst)

a    0
b    1
c    2
e    3
d    4
dtype: int64

In [134]:
# Объедините два pandas.Series (s1, s2) таким образом чтобы получился pandas.DataFrame не используя конструктор!

import numpy as np
import pandas as pd

s1 = pd.Series(list('abced'))
s2 = pd.Series(np.arange(5))

pd.concat([s1, s2], axis=1)

0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4

In [135]:
# Объедините два pandas.Series (переменные s1, s2) таким образом чтобы получился pandas.DataFrame.

import numpy as np
import pandas as pd

s1 = pd.Series(list('abced'))
s2 = pd.Series(np.arange(5))

pd.concat([s1, s2], axis=1, keys=["col1", "col2"])

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [136]:
# Присвойте индексу pandas.Series имя 'characters'.

import pandas as pd

s = pd.Series(list('abced'))
s.name = 'characters'
s

0    a
1    b
2    c
3    e
4    d
Name: characters, dtype: object

In [137]:
# Получите элементы s1, которые не присутствуют в s2.

import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

s1[~s1.isin(s2)]

0    1
1    2
2    3
dtype: int64

In [138]:
# Создайте новый pandas.Series из элементов, которые присутствуют только в одном из двух pandas.Series (переменные s1, s2).
# Если элемент присутствует в двух Series, то выводить его не надо.

import pandas as pd
import numpy as np

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([4, 5, 6, 7, 8])

res = pd.Series(np.union1d(s1, s2))
s12 = pd.Series(np.intersect1d(s1, s2))
res[~res.isin(s12)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [139]:
# Имея данные в pandas.Series (переменная s1) рассчитайте:

#    наименьшее значение
#    25 перцентиль
#    медиану
#    75 перцентиль
#    наибольшее значение

import pandas as pd
import numpy as np

lst = [
    12.53904795, 5.68886327, 16.24734871, 9.60194377, 5.55134259, 5.59100805,
    10.09319475, 11.18922311, 10.06774274, 1.822353
]

s1 = pd.Series(lst)
np.percentile(s1, [0, 25, 50, 75, 100])

array([ 1.822353  ,  5.61547186,  9.83484325, 10.91521602, 16.24734871])

In [140]:
# Определите сколько раз встречается каждое значение в исходном pandas.Series (переменная s).

import pandas as pd

s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))
s.value_counts()

a    8
b    7
c    6
e    5
d    4
h    3
f    2
g    1
dtype: int64

# Step 1.2

In [141]:
# Доработайте код таким образом, чтобы оставить только 2 наиболее встречающихся значения, а для остальных установите значение 'Yet another value'

import pandas as pd

s = pd.Series(list('abdcbdhafceeabcahbcaedadaecbbbecafgh'))
r = s.value_counts().head(2).index
s[~s.isin(r)] = 'Yet another value'
s

0                     a
1                     b
2     Yet another value
3     Yet another value
4                     b
5     Yet another value
6     Yet another value
7                     a
8     Yet another value
9     Yet another value
10    Yet another value
11    Yet another value
12                    a
13                    b
14    Yet another value
15                    a
16    Yet another value
17                    b
18    Yet another value
19                    a
20    Yet another value
21    Yet another value
22                    a
23    Yet another value
24                    a
25    Yet another value
26    Yet another value
27                    b
28                    b
29                    b
30    Yet another value
31    Yet another value
32                    a
33    Yet another value
34    Yet another value
35    Yet another value
dtype: object

In [142]:
# Разбейте все значения из pandas.Series (переменная s1) на 3 интервала равного размера.

import pandas as pd

s1 = pd.Series(reversed(range(0, 10)))
pd.qcut(s1, 3)

0       (6.0, 9.0]
1       (6.0, 9.0]
2       (6.0, 9.0]
3       (3.0, 6.0]
4       (3.0, 6.0]
5       (3.0, 6.0]
6    (-0.001, 3.0]
7    (-0.001, 3.0]
8    (-0.001, 3.0]
9    (-0.001, 3.0]
dtype: category
Categories (3, interval[float64, right]): [(-0.001, 3.0] < (3.0, 6.0] < (6.0, 9.0]]

In [143]:
# Преобразуйте pandas.Series (переменная s1) в pandas.DataFrame размером 2 х 5.

import pandas as pd
import numpy as np

s1 = pd.Series(range(0, 10))
pd.DataFrame(np.array(s1).reshape(2, 5))

0  1  2  3  4
0  0  1  2  3  4
1  5  6  7  8  9

In [144]:
# Найдите индексы значений, которые кратны 2.

import pandas as pd
import numpy as np

s1 = pd.Series([5, 10, 2, 3, 9, 12, 1])
np.argwhere(s1.to_numpy() % 2 == 0)

array([[1],
       [2],
       [5]])

In [145]:
# Создайте новый pandas.Series из элементов, которые находятся по индексам: 0, 7, 12, 15, 19

import pandas as pd

s1 = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

s1.take([0, 7, 12, 15, 19])

0     a
7     h
12    m
15    p
19    t
dtype: object

In [146]:
# Преобразуйте элементы pandas.Series (переменная s1) из строк в даты

import pandas as pd

s1 = pd.Series([
    '01 Jan 2022', '02-02-2022', '20220303', '2022/04/04', '2022-05-05',
    '2022-06-06T12:20'
])
pd.to_datetime(s1)

0   2022-01-01 00:00:00
1   2022-02-02 00:00:00
2   2022-03-03 00:00:00
3   2022-04-04 00:00:00
4   2022-05-05 00:00:00
5   2022-06-06 12:20:00
dtype: datetime64[ns]

In [147]:
# Объект pandas.Series (переменная s1) содержит некоторые числовые значения.
# Для значений хранящихся в s2 определите индексы под которыми они хранятся  в s1.

import pandas as pd

s1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
s2 = pd.Series([1, 3, 10, 13])

s1[s1.isin(s2)].sort_values().index.to_list()

[5, 4, 0, 8]

In [148]:
# Даны следующие ряды данных:
# s_forecast - ряд прогнозных значений
# s_real - ряд фактических значений
# Вычислите среднеквадратичную ошибку.

import pandas as pd

s_forecast = pd.Series(range(10))
s_real = pd.Series(reversed(range(10)))

((s_forecast - s_real)**2).mean()

33.0

In [149]:
# Измените первый символ каждого слова на верхний регистр.

import pandas as pd

s1 = pd.Series(['the', 'weather', 'is', 'fine'])

s1.apply(lambda x: x.capitalize())

0        The
1    Weather
2         Is
3       Fine
dtype: object

In [150]:
# Подсчитайте количество символов в каждом слове.

import pandas as pd

s1 = pd.Series(['the', 'weather', 'is', 'fine'])

s1.str.len()

0    3
1    7
2    2
3    4
dtype: int64

# Step 1.3

In [151]:
# Вытяните день месяца, номер недели, день года и день недели из серии (s1)

import pandas as pd
import numpy as np

s1 = pd.Series([
    '05 Jan 2021', '02-04-2021', '20210403', '2021/06/04', '2021-03-05',
    '2021-03-06T12:20'
])

s2 = pd.to_datetime(s1)
print("Date: ", s2.dt.day.to_list())
print("Week number: ", s2.dt.isocalendar().week.to_list())
print("Day number of year: ", s2.dt.dayofyear.to_list())
print("Day of week: ", s2.dt.day_name().to_list())

Date:  [5, 4, 3, 4, 5, 6]
Week number:  [1, 5, 13, 22, 9, 9]
Day number of year:  [5, 35, 93, 155, 64, 65]
Day of week:  ['Tuesday', 'Thursday', 'Saturday', 'Friday', 'Friday', 'Saturday']


In [152]:
# Измените даты лежащие в серии (s1) таким образом чтобы они начинались с 10-го числа соответствующего месяца.

import pandas as pd
import numpy as np

s1 = pd.Series(['Jan 2022', 'Feb 2022', 'Mar 2022'])
s2 = pd.to_datetime(s1)
s2 + pd.Timedelta(days=9)

0   2022-01-10
1   2022-02-10
2   2022-03-10
dtype: datetime64[ns]

In [153]:
# Из серии (s1) вытяните слова, содержащие не менее 2 гласных.

import pandas as pd
import numpy as np

s1 = pd.Series(['Apple', 'Orange', 'Plan', 'Sky', 'Money'])

s1[s1.str.lower().str.count(r'[aeiou]') > 1]

0     Apple
1    Orange
4     Money
dtype: object

In [154]:
# Извлеките корректные почтовые адреса из серии (s1). Используйте pattern для этой задачи.

import pandas as pd
import numpy as np

s1 = pd.Series([
    'teach pandas at stepik.com', 'help@stepik.com', 'user@t.co',
    'lovepandas@google.com'
])

pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
s1[s1.str.match(pattern)]

1          help@stepik.com
2                user@t.co
3    lovepandas@google.com
dtype: object

In [155]:
# Вычислите среднее значение веса каждого фрукта.

import pandas as pd
import numpy as np

fruit_list = [
    'banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana',
    'carrot', 'apple', 'carrot'
]
weights_list = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

fruits = pd.Series(fruit_list)
weights = pd.Series(weights_list)

weights.groupby(fruits).mean()

apple     6.0
banana    4.0
carrot    5.8
dtype: float64

In [156]:
# Вычислить евклидово расстояние между рядами (точками) X и Y

import pandas as pd
import numpy as np

X = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Y = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

np.sqrt(sum((X - Y)**2))

18.16590212458495

In [157]:
# Определите индексы пиков (значения, окруженные меньшими значениями с обеих сторон).

import pandas as pd
import numpy as np

s1 = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
s2 = s1.shift(1)
s3 = s1.shift(-1)
np.array(s1[(s1 > s2) & (s1 > s3)].index)

array([1, 5, 7])

In [158]:
# В серии (s1) находятся даты с 1 по 8 января 2022 года. Однако некоторые даты и значения к датам пропущены.
# Сделайте так, чтобы все отсутствующие даты отображались и заполнялись значением из предыдущей даты.

import pandas as pd
import numpy as np

s1 = pd.Series([1, 10, 3, np.nan],
               index=pd.to_datetime(
                   ['2022-01-01', '2022-01-03', '2022-01-06', '2022-01-08']))
s1.asfreq('D').fillna(method='ffill')

2022-01-01     1.0
2022-01-02     1.0
2022-01-03    10.0
2022-01-04    10.0
2022-01-05    10.0
2022-01-06     3.0
2022-01-07     3.0
2022-01-08     3.0
Freq: D, dtype: float64

In [159]:
# Отредактируйте название колонок датафрейма (df) следующим образом:
# 1. user -> user_name
# 2. все точки в названии колонок заменить нижним подчёркиванием
# Выведите названия колонок после преобразования.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    data={
        'user': ['Ivan', 'Petr', 'Alex'],
        'user.balance': [500, 200, 0],
        'user.age': [34, 25, 18],
        'user.group': ['A', 'B', 'A']
    })

pd.Index(
    pd.Series(df.columns).replace(["user$", "\."], ["user_name", "_"],
                                  regex=True))

Index(['user_name', 'user_balance', 'user_age', 'user_group'], dtype='object')

In [160]:
# Проверьте, имеются ли пропущенные значения в датафрейме (df).

import pandas as pd
import numpy as np

df = pd.DataFrame(
    data={
        'user': ['Ivan', 'Petr', 'Alex'],
        'user.balance': [500, None, 0],
        'user.age': [34, 25, 18],
        'user.group': ['A', 'B', 'A']
    })

np.any(df.isna())

True

# Step 1.4

In [161]:
# Подсчитайте количество пропущенных значений в каждом столбце.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    data={
        'user': ['Ivan', 'Petr', 'Alex', 'Den'],
        'user.balance': [500, None, 0, None],
        'user.age': [34, None, 18, 43],
        'user.group': ['A', 'B', 'A', 'B']
    })

df.isna().sum()

user            0
user.balance    2
user.age        1
user.group      0
dtype: int64

In [162]:
# Замените отсутствующие значения в столбцах user.speed и user.bag_weight их соответствующими средними значениями.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    data={
        'user': ['Ivan', 'Petr', 'Alex', 'Den'],
        'user.speed': [40, None, 42, 35],
        'user.bag_weight': [8, None, 2, 4]
    })

means = df.mean(numeric_only=True)
df.fillna(means)[['user.speed', 'user.bag_weight']]

user.speed  user.bag_weight
0        40.0         8.000000
1        39.0         4.666667
2        42.0         2.000000
3        35.0         4.000000

In [163]:
# Используйте метод apply, чтобы заменить отсутствующие значения в user.speed средним значением столбца, а в user.bag_weight — медианой столбца.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    data={
        'user': ['Ivan', 'Petr', 'Alex', 'Den'],
        'user.speed': [40, None, 42, 35],
        'user.bag_weight': [8, None, 2, 4]
    })


def foo(x):
    if x.name == "user.bag_weight":
        return x.fillna(x.median())
    elif x.name == "user.speed":
        return x.fillna(x.mean())
    else:
        return x


df.apply(foo)

user  user.speed  user.bag_weight
0  Ivan        40.0              8.0
1  Petr        39.0              4.0
2  Alex        42.0              2.0
3   Den        35.0              4.0

In [164]:
# Поменяйте столбцы А и Е местами в датафрейме:

import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df.reindex(columns=list('ebcda'))

e   b   c   d   a
0   4   1   2   3   0
1   9   6   7   8   5
2  14  11  12  13  10
3  19  16  17  18  15

In [165]:
# Поменяйте порядок столбцов в датафрейме от Е до А.

import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df.reindex(columns=df.columns.sort_values(ascending=False))

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

In [166]:
# Выведите на экран строки датафрейма с шагом 2.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    data={
        'user': ['Ivan', 'Petr', 'Alex', 'Den', 'Viktor'],
        'user.speed': [40, None, 42, 35, 60],
        'user.bag_weight': [8, None, 2, 4, 19]
    })

df[df.index % 2 == 0]

user  user.speed  user.bag_weight
0    Ivan        40.0              8.0
2    Alex        42.0              2.0
4  Viktor        60.0             19.0

In [167]:
# Создайте составной индекс на основе колонок user и user.number для датафрейма:

import pandas as pd
import numpy as np

df = pd.DataFrame(
    data={
        'user': ['Ivan', 'Petr', 'Alex', 'Den', 'Viktor'],
        'user.number': ['222-333', None, '222-555', '222-666', '222-777'],
        'user.speed': [40, None, 42, 35, 60],
        'user.bag_weight': [8, None, 2, 4, 19]
    })

df.loc[:, "user.number"].fillna("missing", inplace=True)
df.index = df.loc[:, 'user'] + "_" + df.loc[:, 'user.number']
df

user user.number  user.speed  user.bag_weight
Ivan_222-333      Ivan     222-333        40.0              8.0
Petr_missing      Petr     missing         NaN              NaN
Alex_222-555      Alex     222-555        42.0              2.0
Den_222-666        Den     222-666        35.0              4.0
Viktor_222-777  Viktor     222-777        60.0             19.0

In [168]:
# Для столбца А найдите индекс строки в которой находится второе наибольшее значение.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    [[16, 24, 29], [1, 10, 16], [26, 21, 10], [3, 3, 8], [6, 17, 17],
     [2, 25, 14], [9, 13, 21], [27, 24, 17], [19, 29, 1], [20, 24, 6]],
    columns=list('abc'))

df.sort_values("a").index[-2]

2

In [169]:
# Выведите последние две строки датафрейма, сумма ячеек которых больше 100.

import pandas as pd
import numpy as np

df = pd.DataFrame([[23, 33, 16, 35], [24, 20, 13, 10], [32, 33, 30, 28],
                   [13, 32, 36, 18], [25, 27, 31, 10], [35, 13, 36, 21],
                   [32, 32, 25, 17], [34, 24, 23, 19]])

df[df.sum(axis=1) > 100].tail(2)

0   1   2   3
5  35  13  36  21
6  32  32  25  17

# Step 1.5

In [170]:
# Выведите на экран сводку основной информации о датафрейме.

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [171]:
# Выведите на экран первые три записи датафрейма.

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [172]:
# Выведите на экран данные, которые хранятся в строках [3, 4, 8] и колонках ['animal', 'age'].

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######

df.iloc[[3, 4, 8], [0, 1]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [173]:
# Выберите только те строки, в которых количество посещений (visits) больше 2.

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.loc[df['visits'] > 2]

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [174]:
# Выберите строки датафрейма  в которых animal = cat, а age < 3.

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.query("animal=='cat' & age<3")

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [175]:
# В строке f замените значение в колонке age на 1.5

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.loc["f", "age"] = 1.5
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [176]:
# Посчитайте итоговое количество посещений (visits)

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df["visits"].sum()

19

In [177]:
# Посчитайте средний возраст каждого вида животного (animal)

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

In [178]:
# Отсортируйте датафрейм по столбцу age в порядке убывания, а затем по столбцу visits в порядке возрастания.

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.sort_values(['age', 'visits'], ascending=[False, True])

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

In [179]:
# Столбец priority содержит строковые значения yes и no. Замените их на булевы True и False

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df['priority'].replace(regex={'yes': True, 'no': False}, inplace=True)
df

animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False

In [180]:
# Определите средний возраст для каждого типа животного и количества посещений.

import pandas as pd
import numpy as np

data = {
    'animal':
    ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority':
    ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

#### YOUR ANSWER BELOW THIS LINE ######
df.pivot_table(columns='visits', index='animal', values='age')

visits    1    2    3
animal               
cat     2.5  NaN  2.5
dog     3.0  6.0  NaN
snake   4.5  0.5  NaN

# Step 1.6

In [181]:
# Вычтите среднее значение строки из каждого элемента в строке.

import pandas as pd
import numpy as np

df = pd.DataFrame([[0.020448, 0.456925, 0.992258],
                   [0.743399, 0.555486, 0.089364],
                   [0.094699, 0.283184, 0.216221]])

df.sub(df.mean(axis=1), axis=0)

0         1         2
0 -0.469429 -0.032952  0.502381
1  0.280649  0.092736 -0.373386
2 -0.103336  0.085149  0.018186

In [182]:
# В каком столбце чисел сумма наименьшая? Выведите на экран название этого столбца.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    [[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364],
     [0.094699, 0.283184, 0.216221]],
    columns=list('abc'))

df.sum().idxmin()

'a'

In [183]:
# Как подсчитать, сколько уникальных строк имеет датафрейм (т. е. игнорировать все повторяющиеся строки)?

import pandas as pd
import numpy as np

df = pd.DataFrame(
    [[0.020448, 0.456925, 0.992258], [0.743399, 0.555486, 0.089364],
     [0.020448, 0.456925, 0.992258], [0.094699, 0.283184, 0.216221]],
    columns=list('abc'))
df.duplicated(keep=False).sum()

2

In [184]:
# Имеется датафрейм состоящий из 10 столбцов чисел с плавающей запятой.
# Ровно 5 записей в каждой строке являются значениями NaN.
# Для каждой строки датафрейма найдите столбец, содержащий третье значение NaN.

import pandas as pd
import numpy as np

nan = np.nan

data = [[0.04, nan, nan, 0.25, nan, 0.43, 0.71, 0.51, nan, nan],
        [nan, nan, nan, 0.04, 0.76, nan, nan, 0.67, 0.76, 0.16],
        [nan, nan, 0.5, nan, 0.31, 0.4, nan, nan, 0.24, 0.01],
        [0.49, nan, nan, 0.62, 0.73, 0.26, 0.85, nan, nan, nan],
        [nan, nan, 0.41, nan, 0.05, nan, 0.61, nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)
df.apply(lambda x: x[x.isna()].index[2], axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: object

In [185]:
# Датафрейм содержит колонку grps (название некоторой группы) и колонку целочисленных значений vals.
# Для каждой группы найдите сумму трех наибольших значений.

import pandas as pd
import numpy as np

df = pd.DataFrame({
    'grps':
    list('aaabbcaabcccbbc'),
    'vals': [12, 345, 3, 1, 45, 14, 4, 52, 54, 23, 235, 21, 57, 3, 87]
})

df.groupby('grps').agg(
    lambda x: x.sort_values(ascending=False).head(3).sum()).squeeze()

grps
a    409
b    156
c    345
Name: vals, dtype: int64

In [186]:
# Датафрейм df имеет два целочисленных столбца «A» и «B». Значения в «A» находятся в диапазоне от 1 до 100 (включительно).
# Для каждой группы из 10 последовательных целых чисел в столбце А (т. е. (0, 10], (10, 20], ...)
# вычислите сумму соответствующих значений в столбце B.

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)),
                  columns=["A", "B"])
df['B'].groupby(
    pd.cut(df['A'], bins=pd.interval_range(start=0, end=100, freq=10))).sum()

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64

In [187]:
# Создайте список индексов столбцов и строк для 3 самых больших значений в предлагаемом датафрейме.

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
df.unstack().sort_values().tail(3).index.to_list()

[(5, 7), (6, 4), (2, 5)]

In [188]:
# Создайте новый столбец patched_vals, который содержит те же значения, что и vals,
# но отрицательные значения заменить средним значением группы.

import pandas as pd
import numpy as np

df = pd.DataFrame({
    "vals": np.random.RandomState(31).randint(-30, 30, size=15),
    "grps": np.random.RandomState(31).choice(["A", "B"], 15)
})

df['patched_vals'] = df['vals']
df.loc[df['patched_vals'] < 0, 'patched_vals'] = np.nan
df.groupby('grps').apply(lambda x: x.fillna(x['patched_vals'].mean()))

vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6

In [189]:
# Найдите сумму всех значений, которые указаны для среды (Wednesday)

import pandas as pd
import numpy as np

dti = pd.date_range(start='2021-01-01', end='2021-12-31', freq='B')
s = pd.Series(np.random.RandomState(30).rand(len(dti)), index=dti)
s[s.index.dayofweek == 2].sum()

23.508792429234397

In [190]:
# Для каждого месяца найдите среднее значение.

import pandas as pd
import numpy as np

dti = pd.date_range(start='2021-01-01', end='2021-12-31', freq='B')
s = pd.Series(np.random.RandomState(30).rand(len(dti)), index=dti)

s.groupby(pd.Grouper(freq='M')).mean()

2021-01-31    0.507726
2021-02-28    0.462692
2021-03-31    0.478605
2021-04-30    0.564210
2021-05-31    0.387735
2021-06-30    0.451999
2021-07-31    0.541958
2021-08-31    0.553241
2021-09-30    0.507650
2021-10-31    0.453517
2021-11-30    0.490528
2021-12-31    0.495812
Freq: M, dtype: float64

# Step 1.7

In [191]:
# Превратите датафрейм в квадрат с максимально возможной длиной стороны n, убрав отрицательные значения.
# При необходимости удалите наименьшие значения.
# Порядок положительных чисел в результате должен оставаться таким же, как и в оригинале.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.random.RandomState(30).randint(-20, 50, 100).reshape(10, -1))

df = df.to_numpy(dtype="float64")
df = df[df > 0]
n = int(np.floor(len(df)**0.5))
df[sorted(df.argsort()[-n**2:])].reshape(n, n)

array([[17., 17., 25., 25., 33., 26., 21., 45.],
       [29., 25., 41., 15., 42., 26., 25., 44.],
       [42., 30., 13., 35., 38., 37., 24., 17.],
       [37., 19., 13., 27., 19., 16., 20., 34.],
       [49., 10., 29., 32., 24., 41., 14., 23.],
       [40., 31., 21., 36., 19., 13.,  8., 38.],
       [25., 28., 35., 25., 11.,  9., 24.,  9.],
       [31., 35., 32., 41., 19., 10., 24., 27.]])

In [192]:
#Поменяйте местами строки 1 и 2

import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(25).reshape(5, -1))
df.reindex([0, 2, 1, 3, 4]).reset_index(drop=True)

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

In [193]:
#Измените порядок строк датафрейма таким образом, чтобы последние стали первыми, а первые последними (reverse).

import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(25).reshape(5, -1))
df.reindex(df.index.sort_values(ascending=False))

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [194]:
#Выполните one-hot encoding для столбца А и добавьте результат к датафрейму

import pandas as pd
import numpy as np

df = pd.DataFrame(np.arange(25).reshape(5, -1), columns=list('abcde'))

pd.concat([pd.get_dummies(df['a']), df.reindex(columns=list('bcde'))], axis=1)

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [195]:
#Определите имя столбца с наибольшим количеством строковых максимумов.

import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.random.RandomState(30).randint(1, 100, 40).reshape(10, -1))

df.rank(axis=1,
        method='max').agg(lambda x: x[x == x.max()].sum()).argsort().max()

3

In [196]:
#Создайте новый столбец таким образом, чтобы каждая строка содержала номер ближайшей строки-записи по евклидову расстоянию.

import pandas as pd
import numpy as np


def solution(df):

    def foo(x):
        return df.apply(lambda y: int(round(np.sqrt(np.sum((x - y)**2)))),
                        axis=1)

    _df = df.apply(foo, axis=1)
    df['nearest_row'] = _df.idxmax()
    df['dist'] = _df.max()
    return df


df = pd.DataFrame(np.random.RandomState(30).randint(1, 100,
                                                    40).reshape(10, -1),
                  columns=list('pqrs'),
                  index=list('abcdefghij'))
solution(df)

p   q   r   s nearest_row  dist
a  38  38  46  46           f    61
b  13  24   3  54           j   100
c  18  47   4  42           j    97
d   8  66  50  46           f    96
e  62  36  19  19           j   103
f  77  17   7  63           j   107
g  28  47  46  65           h    71
h  63  12  16  24           j   110
i  14  51  34  56           f    77
j  29  59  92  79           h   110

In [197]:
#Определите максимально возможное значение корреляции каждого столбца по сравнению с другими столбцами датафрейма.

import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.RandomState(25).randint(1, 100, 80).reshape(8, -1),
                  columns=list('pqrstuvwxy'),
                  index=list('abcdefgh'))

_df = df.corr().round(2).abs()
_df[_df < 1].max().to_numpy()

array([0.77, 0.64, 0.77, 0.85, 0.62, 0.85, 0.62, 0.67, 0.44, 0.62])

In [198]:
#Определите отношение минимума к максимуму для каждой строки.

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(25).randint(1, 100, 80).reshape(8, -1))

df.min(axis=1) / df.max(axis=1)

0    0.054945
1    0.022222
2    0.023529
3    0.022989
4    0.030303
5    0.032967
6    0.170455
7    0.164835
dtype: float64

In [199]:
#Создайте новый столбец penultimate (с англ. предпоследний), который имеет второе по величине значение каждой строки датафрейма:

import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.RandomState(25).randint(1, 100, 80).reshape(8, -1))
df['penultimate'] = df.apply(lambda x: x.nlargest(2).min(), axis=1)
df

0   1   2   3   4   5   6   7   8   9  penultimate
0   5  63  91  16  62  24  45  51   9  29           63
1   5  90  32  70   2  40   4  89  56   4           89
2  85  46   4   2  23  32  49  48  74  17           74
3  51  86  37  10  33  11  61  48   2  87           86
4  92  50  19  93  37  99  31  39   3   6           93
5  58  74  23  12   3  44  91  62  85  84           85
6  75  18  15  84  38  88  51  52  15  72           84
7  63  91  16  15  77  40  89  47  54  30           89

In [200]:
#Нормализуйте все столбцы датафрейма, вычитая среднее значение столбца и разделив на стандартное отклонение:

import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.RandomState(20).randint(1, 100, 80).reshape(8, -1))
df
round((df - df.mean()) / df.std(), 2)

0     1     2     3     4     5     6     7     8     9
0  1.47 -1.13  1.31 -0.59  1.38 -1.00 -1.27  0.98 -0.46  0.59
1 -0.23  1.07 -0.50  1.08  1.38 -0.47  1.03 -0.97  0.72 -1.08
2 -1.05  1.12 -1.62 -0.65 -0.69  1.07  0.12 -0.67 -1.02  0.68
3  1.02  0.12  0.72  1.02  0.50  1.67 -0.83 -1.17 -0.93  0.71
4 -0.71 -1.45  0.72 -0.92  0.12 -0.78 -1.34  1.11  1.55  0.23
5  0.89  0.50 -0.86 -0.10 -0.87  0.70  0.85 -0.71 -0.58  1.26
6 -0.26  0.58 -0.43  1.34 -0.95 -0.72  0.56  0.22 -0.46 -1.14
7 -1.14 -0.80  0.66 -1.18 -0.87 -0.47  0.89  1.21  1.19 -1.26

# Step 1.8

In [201]:
# Для вас подготовлен датафрейм содержащий имена пользователей и их теги.
# Ваша задача заключается в том чтобы вытянуть самый первый тег из списка и сформировать отдельную колонку:

import pandas as pd


def solution(df):
    #df["user_main_tag"] = df.apply(lambda x: x.str.replace(r"^\['(\w+)'.*", "\g<1>", regex=True)["user_tags"], axis=1)
    df['user_main_tag'] = df['user_tags'].apply(lambda x: eval(x)[0])
    return df


df = pd.DataFrame({
    'user_name': {
        '0': 'Ivan 007',
        '1': 'Petr 911',
        '2': 'Nikolay 112'
    },
    'user_tags': {
        '0': "['sport', 'law', 'cars']",
        '1': "['cars', 'law', 'girls']",
        '2': "['law', 'travels', 'cars']"
    }
})
solution(df)

user_name                   user_tags user_main_tag
0     Ivan 007    ['sport', 'law', 'cars']         sport
1     Petr 911    ['cars', 'law', 'girls']          cars
2  Nikolay 112  ['law', 'travels', 'cars']           law

In [202]:
# Некоторые значения в столбце FlightNumber отсутствуют.
# Значения в столбце должны увеличиваться на 10 с каждой строкой, поэтому в пропусках необходимо установить 10055 и 10075.
# Заполните эти недостающие числа и измените тип столбца с float на int

import pandas as pd
import numpy as np


def solution(df):
    df["FlightNumber"] = df["FlightNumber"].interpolate().astype("int")
    return df


df = pd.DataFrame({
    'From_To': {
        0: 'LoNDon_paris',
        1: 'MAdrid_miLAN',
        2: 'londON_StockhOlm',
        3: 'Budapest_PaRis',
        4: 'Brussels_londOn'
    },
    'FlightNumber': {
        0: 10045.0,
        1: np.nan,
        2: 10065.0,
        3: np.nan,
        4: 10085.0
    },
    'RecentDelays': {
        0: [23, 47],
        1: [],
        2: [24, 43, 87],
        3: [13],
        4: [67, 32]
    },
    'Airline': {
        0: 'KLM(!)',
        1: '<Air France> (12)',
        2: '(British Airways. )',
        3: '12. Air France',
        4: '"Swiss Air"'
    }
})

solution(df)

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

In [203]:
# Разбейте данные из столбца From_To на два столбца From и То. Исходный столбец удалите.

import pandas as pd
import numpy as np


def solution(df):
    df = pd.concat([
        df.drop(columns=["From_To"]), df["From_To"].str.extract(
            r'(?P<From>.*?)_(?P<To>.*)').apply(lambda x: x.str.capitalize())
    ],
                   axis=1)
    return df


df = pd.DataFrame({
    'From_To': {
        0: 'LoNDon_paris',
        1: 'MAdrid_miLAN',
        2: 'londON_StockhOlm',
        3: 'Budapest_PaRis',
        4: 'Brussels_londOn'
    },
    'FlightNumber': {
        0: 10045.0,
        1: np.nan,
        2: 10065.0,
        3: np.nan,
        4: 10085.0
    },
    'RecentDelays': {
        0: [23, 47],
        1: [],
        2: [24, 43, 87],
        3: [13],
        4: [67, 32]
    },
    'Airline': {
        0: 'KLM(!)',
        1: '<Air France> (12)',
        2: '(British Airways. )',
        3: '12. Air France',
        4: '"Swiss Air"'
    }
})

solution(df)

FlightNumber  RecentDelays              Airline      From         To
0       10045.0      [23, 47]               KLM(!)    London      Paris
1           NaN            []    <Air France> (12)    Madrid      Milan
2       10065.0  [24, 43, 87]  (British Airways. )    London  Stockholm
3           NaN          [13]       12. Air France  Budapest      Paris
4       10085.0      [67, 32]          "Swiss Air"  Brussels     London

In [204]:
# В столбце Airline содержатся наименования авиакомпаний.
# Можно заметить, что в названиях присутствуют 'лишние' символы. Выполните преобразование столбца Airline:

import pandas as pd
import numpy as np


def solution(df):
    df["Airline"] = df["Airline"].replace(r'[^a-zA-Z\s]', '',
                                          regex=True).str.strip()
    return df


df = pd.DataFrame({
    'From_To': {
        0: 'LoNDon_paris',
        1: 'MAdrid_miLAN',
        2: 'londON_StockhOlm',
        3: 'Budapest_PaRis',
        4: 'Brussels_londOn'
    },
    'FlightNumber': {
        0: 10045.0,
        1: np.nan,
        2: 10065.0,
        3: np.nan,
        4: 10085.0
    },
    'RecentDelays': {
        0: [23, 47],
        1: [],
        2: [24, 43, 87],
        3: [13],
        4: [67, 32]
    },
    'Airline': {
        0: 'KLM(!)',
        1: '<Air France> (12)',
        2: '(British Airways. )',
        3: '12. Air France',
        4: '"Swiss Air"'
    }
})

solution(df)

From_To  FlightNumber  RecentDelays          Airline
0      LoNDon_paris       10045.0      [23, 47]              KLM
1      MAdrid_miLAN           NaN            []       Air France
2  londON_StockhOlm       10065.0  [24, 43, 87]  British Airways
3    Budapest_PaRis           NaN          [13]       Air France
4   Brussels_londOn       10085.0      [67, 32]        Swiss Air

In [205]:
#Распакуйте данные из RecentDelays по столбцам delay_1 ... delay_n. После распаковки удалите столбец RecentDelays.

import pandas as pd
import numpy as np


def solution(df):

    def foo(x):
        for i, v in enumerate(x):
            df.loc[x.name, f"delay_{i+1}"] = v

    df['RecentDelays'].explode().groupby(level=0).apply(foo)
    df.drop(columns='RecentDelays', inplace=True)
    return df


df = pd.DataFrame({
    'From_To': {
        0: 'LoNDon_paris',
        1: 'MAdrid_miLAN',
        2: 'londON_StockhOlm',
        3: 'Budapest_PaRis',
        4: 'Brussels_londOn'
    },
    'FlightNumber': {
        0: 10045.0,
        1: np.nan,
        2: 10065.0,
        3: np.nan,
        4: 10085.0
    },
    'RecentDelays': {
        0: [23, 47],
        1: [],
        2: [24, 43, 87],
        3: [13],
        4: [67, 32]
    },
    'Airline': {
        0: 'KLM(!)',
        1: '<Air France> (12)',
        2: '(British Airways. )',
        3: '12. Air France',
        4: '"Swiss Air"'
    }
})

solution(df)

From_To  FlightNumber              Airline  delay_1  delay_2  \
0      LoNDon_paris       10045.0               KLM(!)     23.0     47.0   
1      MAdrid_miLAN           NaN    <Air France> (12)      NaN      NaN   
2  londON_StockhOlm       10065.0  (British Airways. )     24.0     43.0   
3    Budapest_PaRis           NaN       12. Air France     13.0      NaN   
4   Brussels_londOn       10085.0          "Swiss Air"     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN

In [206]:
# Замените на 0 все значения на диагоналях матрицы:


import pandas as pd
import numpy as np

def solution(df):
    dn = df.to_numpy()
    np.fill_diagonal(dn, 0)
    np.fill_diagonal(np.fliplr(dn), 0)
    return df

df = pd.DataFrame({0: {0: 10, 1: 41, 2: 50, 3: 31, 4: 94, 5: 16, 6: 29, 7: 89, 8: 23, 9: 98}, 
                   1: {0: 16, 1: 37, 2: 52, 3: 31, 4: 78, 5: 19, 6: 34, 7: 51, 8: 12, 9: 51}, 
                   2: {0: 65, 1: 17, 2: 55, 3: 90, 4: 23, 5: 81, 6: 85, 7: 55, 8: 13, 9: 46}, 
                   3: {0: 29, 1: 12, 2: 78, 3: 13, 4: 24, 5: 72, 6: 97, 7: 35, 8: 93, 9: 41}, 
                   4: {0: 90, 1: 55, 2: 70, 3: 66, 4: 95, 5: 89, 6: 89, 7: 16, 8: 97, 9: 90}, 
                   5: {0: 94, 1: 89, 2: 14, 3: 32, 4: 12, 5: 12, 6: 45, 7: 78, 8: 63, 9: 74}, 
                   6: {0: 30, 1: 63, 2: 26, 3: 58, 4: 29, 5: 18, 6: 6, 7: 89, 8: 58, 9: 38}, 
                   7: {0: 9, 1: 34, 2: 14, 3: 37, 4: 75, 5: 47, 6: 5, 7: 16, 8: 80, 9: 1}, 
                   8: {0: 74, 1: 73, 2: 93, 3: 28, 4: 89, 5: 8, 6: 72, 7: 7, 8: 43, 9: 19}, 
                   9: {0: 1, 1: 79, 2: 87, 3: 19, 4: 10, 5: 76, 6: 89, 7: 86, 8: 58, 9: 24}})

solution(df)


0   1   2   3   4   5   6   7   8   9
0   0  16  65  29  90  94  30   9  74   0
1  41   0  17  12  55  89  63  34   0  79
2  50  52   0  78  70  14  26   0  93  87
3  31  31  90   0  66  32   0  37  28  19
4  94  78  23  24   0   0  29  75  89  10
5  16  19  81  72   0   0  18  47   8  76
6  29  34  85   0  89  45   0   5  72  89
7  89  51   0  35  16  78  89   0   7  86
8  23   0  13  93  97  63  58  80   0  58
9   0  51  46  41  90  74  38   1  19   0

In [207]:
#Создайте два новых столбца, один из которых является lag1 (сдвиг значений столбца А вниз на 1 строку), 
#а другой — lead1 (сдвиг значений столбца B вверх на 1 строку):

import pandas as pd
import numpy as np

def solution(df):
    df['a_lag1'] = df['a'].shift(1)
    df['b_lead1'] = df['b'].shift(-1)
    return df

df = pd.DataFrame({'a': {0: 10, 1: 90, 2: 74, 3: 17, 4: 63}, 
                   'b': {0: 16, 1: 94, 2: 1, 3: 12, 4: 34}, 
                   'c': {0: 65, 1: 30, 2: 41, 3: 55, 4: 73}, 
                   'd': {0: 29, 1: 9, 2: 37, 3: 89, 4: 79}})

solution(df)

a   b   c   d  a_lag1  b_lead1
0  10  16  65  29     NaN     94.0
1  90  94  30   9    10.0      1.0
2  74   1  41  37    90.0     12.0
3  17  12  55  89    74.0     34.0
4  63  34  73  79    17.0      NaN

In [208]:
#В исходном датафрейме содержится информация о затратах во время командировок по каждому месяцу для каждого сотрудника.
#Выполните преобразование датафрейма:

import pandas as pd
import numpy as np


def solution(df):
    df = df.melt(id_vars=['city', 'agent'],
                 var_name='Date',
                 value_name='Value')
    return df


df = pd.DataFrame({
    'city': {
        0: 'Moscow',
        1: 'Berlin',
        2: 'Paris'
    },
    'agent': {
        0: 'Ivan',
        1: 'Valter',
        2: 'Ali Abu'
    },
    'Jan-2022': {
        0: 5000,
        1: 3000,
        2: 2000
    },
    'Feb-2022': {
        0: 3000,
        1: 2000,
        2: 4000
    },
    'March-2022': {
        0: 0,
        1: 5000,
        2: 7000
    }
})

solution(df)

city    agent        Date  Value
0  Moscow     Ivan    Jan-2022   5000
1  Berlin   Valter    Jan-2022   3000
2   Paris  Ali Abu    Jan-2022   2000
3  Moscow     Ivan    Feb-2022   3000
4  Berlin   Valter    Feb-2022   2000
5   Paris  Ali Abu    Feb-2022   4000
6  Moscow     Ivan  March-2022      0
7  Berlin   Valter  March-2022   5000
8   Paris  Ali Abu  March-2022   7000

In [209]:
#Для каждого месяца определите, кто затратил больше всего денег:

import pandas as pd
import numpy as np


def solution(df):
    df = df.groupby(by='Date').apply(
        lambda x: x.nlargest(1, columns=['Value'])).reset_index(
            level=0, drop=True).sort_index(level=0)
    return df


df = pd.DataFrame({
    'city': {
        0: 'Moscow',
        1: 'Berlin',
        2: 'Paris',
        3: 'Moscow',
        4: 'Berlin',
        5: 'Paris',
        6: 'Moscow',
        7: 'Berlin',
        8: 'Paris'
    },
    'agent': {
        0: 'Ivan',
        1: 'Valter',
        2: 'Ali Abu',
        3: 'Ivan',
        4: 'Valter',
        5: 'Ali Abu',
        6: 'Ivan',
        7: 'Valter',
        8: 'Ali Abu'
    },
    'Date': {
        0: 'Jan-2022',
        1: 'Jan-2022',
        2: 'Jan-2022',
        3: 'Feb-2022',
        4: 'Feb-2022',
        5: 'Feb-2022',
        6: 'March-2022',
        7: 'March-2022',
        8: 'March-2022'
    },
    'Value': {
        0: 5000,
        1: 3000,
        2: 2000,
        3: 3000,
        4: 2000,
        5: 4000,
        6: 0,
        7: 5000,
        8: 7000
    }
})

solution(df)

city    agent        Date  Value
0  Moscow     Ivan    Jan-2022   5000
5   Paris  Ali Abu    Feb-2022   4000
8   Paris  Ali Abu  March-2022   7000

In [210]:
#Сгруппируйте все затраты для каждого месяца в список:

import pandas as pd
import numpy as np


def solution(df):
    df = df.groupby('Date')['Value'].apply(list).reset_index(name='values_in_list')
    return df


df = pd.DataFrame({
    'city': {
        0: 'Moscow',
        1: 'Berlin',
        2: 'Paris',
        3: 'Moscow',
        4: 'Berlin',
        5: 'Paris',
        6: 'Moscow',
        7: 'Berlin',
        8: 'Paris'
    },
    'agent': {
        0: 'Ivan',
        1: 'Valter',
        2: 'Ali Abu',
        3: 'Ivan',
        4: 'Valter',
        5: 'Ali Abu',
        6: 'Ivan',
        7: 'Valter',
        8: 'Ali Abu'
    },
    'Date': {
        0: 'Jan-2022',
        1: 'Jan-2022',
        2: 'Jan-2022',
        3: 'Feb-2022',
        4: 'Feb-2022',
        5: 'Feb-2022',
        6: 'March-2022',
        7: 'March-2022',
        8: 'March-2022'
    },
    'Value': {
        0: 5000,
        1: 3000,
        2: 2000,
        3: 3000,
        4: 2000,
        5: 4000,
        6: 0,
        7: 5000,
        8: 7000
    }
})

solution(df)

Date      values_in_list
0    Feb-2022  [3000, 2000, 4000]
1    Jan-2022  [5000, 3000, 2000]
2  March-2022     [0, 5000, 7000]

# Step 1.9

In [211]:
#В датафрейме содержатся классы ABC1 - ABC5. 
#Постройте новый датафрейм, который будет состоять из уникальных пар классов:

import pandas as pd
import numpy as np
from itertools import combinations


def solution(df):
    df = df.join(df, lsuffix='_1', rsuffix='_2', how='cross').set_index(['class_1', 'class_2'])
    df = df.loc[[(a,b) for a,b in df.index if b>a]]
    return df
        


df = pd.DataFrame({
    'class': {
        0: 'ABC1',
        1: 'ABC2',
        2: 'ABC3',
        3: 'ABC4',
        4: 'ABC5'
    },
    'base1': {
        0: 1,
        1: 2,
        2: 3,
        3: 4,
        4: 5
    }
})

solution(df)

base1_1  base1_2
class_1 class_2                  
ABC1    ABC2           1        2
        ABC3           1        3
        ABC4           1        4
        ABC5           1        5
ABC2    ABC3           2        3
        ABC4           2        4
        ABC5           2        5
ABC3    ABC4           3        4
        ABC5           3        5
ABC4    ABC5           4        5

* В результате некоторой выездной проверки, контролёром Петренко была собрана информация о работающих магазинах (наименование, ИНН владельца, адрес магазина)[df_shops]:

* Контролёр Петренко имеет доступ к базе разрешений на торговлю (номер разрешения, ИНН владельца, адрес торговли)[df_licenses]:

* Помогите контролёру Петренко подтянуть информацию о разрешениях на торговлю в его датафрейм. 

In [212]:
import pandas as pd
import numpy as np

# def solution(df_shops, df_licenses):
#     df_shops['rank'] = df_shops.reset_index().groupby(['owner_inn'])['index'].rank()
#     df_licenses['rank'] = df_licenses.reset_index().groupby(['owner_inn'])['index'].rank()
#     df = pd.merge(df_shops, df_licenses, on=['rank', 'owner_inn', 'address'], how='left') \
#         [['shop_name', 'owner_inn', 'address', 'reg_number']].fillna('-')

#     return df


def solution(df_shops: pd.DataFrame, df_licenses: pd.DataFrame):
    df_shops['rank'] = df_shops.groupby('owner_inn')['owner_inn'].apply(
        lambda x: x.astype('int64').rank(method='first'))
    df_licenses['rank'] = df_licenses.groupby('owner_inn')['owner_inn'].apply(
        lambda x: x.astype('int64').rank(method='first'))
    df_shops = df_shops.merge(df_licenses,
                              on=['owner_inn', 'address', 'rank'],
                              how='left').fillna('-').drop(columns=['rank'])
    return df_shops


df_shops = pd.DataFrame({
    'shop_name': {
        0: 'Детские игрушки',
        1: 'Продукты',
        2: 'Хоз. товары',
        3: 'Бытовая химия',
        4: 'Военторг',
        5: 'АлкоМаркет',
        6: 'Фрукты-Овощи',
        7: 'Цветы 24'
    },
    'owner_inn': {
        0: '7700000001',
        1: '7700000001',
        2: '7700000002',
        3: '7700000002',
        4: '7700000003',
        5: '7700000004',
        6: '7700000005',
        7: '7700000006'
    },
    'address': {
        0: 'ул. Академика Иванова, 1',
        1: 'ул. Академика Иванова, 1',
        2: 'ул. Летчиков, 5',
        3: 'ул. Летчиков, 5',
        4: 'ул. Автомобилистов, 6',
        5: 'ул. Автомобилистов, 6',
        6: 'ул. Первомайская, 66',
        7: 'ул. Степика, 123'
    }
})
df_licenses = pd.DataFrame({
    'reg_number': {
        0: 'A-000-001',
        1: 'A-000-002',
        2: 'A-000-003',
        3: 'A-000-005',
        4: 'A-000-006',
        5: 'A-000-007'
    },
    'owner_inn': {
        0: '7700000001',
        1: '7700000001',
        2: '7700000002',
        3: '7700000003',
        4: '7700000004',
        5: '7700000005'
    },
    'address': {
        0: 'ул. Академика Иванова, 1',
        1: 'ул. Академика Иванова, 1',
        2: 'ул. Летчиков, 5',
        3: 'ул. Автомобилистов, 6',
        4: 'ул. Автомобилистов, 8',
        5: 'ул. Первомайская, 66'
    }
})

solution(df_shops, df_licenses)

shop_name   owner_inn                   address reg_number
0  Детские игрушки  7700000001  ул. Академика Иванова, 1  A-000-001
1         Продукты  7700000001  ул. Академика Иванова, 1  A-000-002
2      Хоз. товары  7700000002           ул. Летчиков, 5  A-000-003
3    Бытовая химия  7700000002           ул. Летчиков, 5          -
4         Военторг  7700000003     ул. Автомобилистов, 6  A-000-005
5       АлкоМаркет  7700000004     ул. Автомобилистов, 6          -
6     Фрукты-Овощи  7700000005      ул. Первомайская, 66  A-000-007
7         Цветы 24  7700000006          ул. Степика, 123          -

In [213]:
#Для каждой группы определите номер уникального значения:

import pandas as pd
import numpy as np


def solution(df):
    df['group_val_id'] = df.groupby([
        'group'
    ]).apply(lambda x: x.groupby('value').ngroup() + 1).reset_index(
        drop=True).astype("int8")
    print(df.info())
    return df


df = pd.DataFrame({
    'group': {
        0: 1,
        1: 1,
        2: 1,
        3: 1,
        4: 1,
        5: 1,
        6: 1,
        7: 2,
        8: 2,
        9: 2,
        10: 2,
        11: 2
    },
    'value': {
        0: 'a',
        1: 'a',
        2: 'b',
        3: 'b',
        4: 'b',
        5: 'b',
        6: 'c',
        7: 'd',
        8: 'd',
        9: 'd',
        10: 'd',
        11: 'e'
    }
})

solution(df)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   group         12 non-null     int64 
 1   value         12 non-null     object
 2   group_val_id  12 non-null     int8  
dtypes: int64(1), int8(1), object(1)
memory usage: 300.0+ bytes
None


group value  group_val_id
0       1     a             1
1       1     a             1
2       1     b             2
3       1     b             2
4       1     b             2
5       1     b             2
6       1     c             3
7       2     d             1
8       2     d             1
9       2     d             1
10      2     d             1
11      2     e             2

# Step 2 (Numpy)
* ## Step 2.1

In [214]:
#Создайте нулевой вектор размера 10.

import numpy as np

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [215]:
#Как узнать размер в памяти массива Z.

import numpy as np

Z = np.zeros((10, 10))

print(f"{Z.nbytes} bytes")

800 bytes


In [216]:
#Создайте нулевой вектор размера 10, но пятое значение равно 1

import numpy as np

a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [217]:
#Создайте вектор со значениями в диапазоне от 10 до 20

import numpy as np

np.arange(10, 21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [218]:
#Разверните вектор Z (первый элемент становится последним, а последний первым)
import numpy as np

Z = np.arange(10)
Z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [219]:
#Создайте матрицу 3x3 со значениями в диапазоне от 0 до 8. Используйте arange и reshape.

import numpy as np

np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [220]:
#Найдите индексы ненулевых элементов массива Z. Ответ представьте в виде одномерного массива.

import numpy as np


def solution(Z):
    M = Z.nonzero()
    return M

In [221]:
#Создайте единичную матрицу 3х3
import numpy as np

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [222]:
#Найдите наименьшее и наибольшее значение массива Z

import numpy as np

Z = np.array([1, 2, 0, 0, 4, 0])
print(Z.max(), Z.min())

4 0


In [223]:
#Создайте матрицу размером 5х5, где по краям будут единицы, а в центре нули.

import numpy as np

z = np.ones(shape=(5, 5))
z[1:-1, 1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Step 2.2

In [224]:
#Создайте матрицу 5x5 со значениями 1,2,3,4 чуть ниже диагонали

import numpy as np

#np.diag(np.arange(1, 5), -1)

z = np.zeros((5, 5))
np.fill_diagonal(z[1:, :-1], np.arange(1, 5))
z.astype("int64")

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [225]:
#Создайте матрицу 8x8 и заполните ее в шахматном порядке.

import numpy as np

# print(np.indices((8,8)).sum(axis=0) % 2)

z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [226]:
#Нормализуйте матрицу Z

import numpy as np

Z = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1], [1, 2, 3, 4, 5],
              [5, 4, 3, 2, 1]])
(Z - Z.mean()) / Z.std()

array([[-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [ 1.41421356,  0.70710678,  0.        , -0.70710678, -1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [ 1.41421356,  0.70710678,  0.        , -0.70710678, -1.41421356]])

In [227]:
#Выполните матричное умножение А и B

import numpy as np

A = np.ones((5, 3))
B = np.ones((3, 2))

np.dot(A, B)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [228]:
#Выполните умножение на -1 те значения, которые больше 3, но меньше 8.

import numpy as np

Z = np.arange(11)

np.where((Z > 3) & (Z < 8), -1 * Z, Z)

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [229]:
#Как найти общие значения между двумя массивами Z1 и Z2?

import numpy as np

Z1 = np.array([1, 2, 3, 4, 5])
Z2 = np.array([6, 7, 8, 9, 5, 4])

np.intersect1d(Z1, Z2)

array([4, 5])

In [230]:
#Вычислите ((A+B)*(-A/2)) без копирования массивов.

import numpy as np

A = np.ones(3) * 1
B = np.ones(3) * 2

np.multiply(np.add(A, B), np.divide(np.negative(A), 2))

array([-1.5, -1.5, -1.5])

In [231]:
#Создайте матрицу 5x5 со значениями строк в диапазоне от 0 до 4.

import numpy as np

np.ones((5, 5)) * np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [232]:
#Создайте вектор размера 10 со значениями в диапазоне от 0 до 1. (0 и 1 не должны входить)

import numpy as np

np.linspace(0, 1, num=11, endpoint=False)[-10:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [233]:
#Выполните сортировку массива Z

import numpy as np

Z = np.array([6, 9, 5, 7, 8, 4])

np.sort(Z)

array([4, 5, 6, 7, 8, 9])

# Step 2.3

In [234]:
#Чему равен результат операции:

import numpy as np
import pandas as pd

pd.Series([
    0 * np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, np.nan
    in set([np.nan]), 0.3 == 3 * 0.1,
    np.array(0) / np.array(0),
    np.array(0) // np.array(0),
    np.array([np.nan]).astype(int).astype(float), 2 << np.arange(5) >> 2
])

/tmp/ipykernel_4507/1554705133.py:9: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0),
/tmp/ipykernel_4507/1554705133.py:10: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0),


0                         NaN
1                       False
2                       False
3                         NaN
4                        True
5                       False
6                         NaN
7                           0
8    [-9.223372036854776e+18]
9             [0, 1, 2, 4, 8]
dtype: object

# Step 2.4

In [235]:
#Проверьте, равны ли элементы массивов A и B в пределах допуска, который равен 1
#(проверка на приблизительное равенство).

import numpy as np

A = np.array([1, 2, 3, 4, 5])
B = np.array([2, 3, 4, 5, 6])

# np.all(np.abs(A-B) <= 1)
np.allclose(A, B, atol=1)

True

In [236]:
# Матрица Z размером 10x2, содержит декартовы координаты. Преобразуйте их в полярные координаты.

import numpy as np

Z = np.array([[0.64414354, 0.38074849], [0.66304791, 0.16365073],
              [0.96260781, 0.34666184], [0.99175099, 0.2350579],
              [0.58569427, 0.4066901], [0.13623432, 0.54413629],
              [0.51817635, 0.76685511], [0.93385014, 0.08970338],
              [0.19577126, 0.99419368], [0.2351805, 0.23898637]])

print(np.sqrt(Z[:, 1]**2 + Z[:, 0]**2))
print(np.arctan2(Z[:, 1], Z[:, 0]))

[0.74825819 0.68294516 1.02312669 1.0192263  0.71304601 0.56093145
 0.92551255 0.93814859 1.01328548 0.33529741]
[0.53384421 0.24197957 0.34566872 0.23271877 0.60693925 1.32547133
 0.97655486 0.09576376 1.37636924 0.79342443]


In [237]:
#Замените максимальное значение массива на -1

import numpy as np

Z = np.array([1, 6, 3, 9, 3, 6, 7, 10, 3])

Z[np.argsort(Z)[-1]] = -1
Z

array([ 1,  6,  3,  9,  3,  6,  7, -1,  3])

In [238]:
#Имея массивы X и Y постройте матрицу Коши: C (Cij =1/(xi - yj))а затем посчитайте детерминант.

import numpy as np

X = np.arange(8)
Y = X + 0.5

C = np.zeros((8, 8))
for j, v in enumerate(Y):
    C[j] = 1 / (X - v)

np.linalg.det(C)

3638.1636371179666

In [239]:
#Найдите ближайшее значение (к заданному скаляру v) в векторе Z?

import numpy as np

Z = np.arange(100)
v = 68.2139380784148

Z[np.abs(Z - v).argmin()]

68